CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)   NOT NULL,
    description TEXT,
    price       DECIMAL(19, 2) NOT NULL,
    category    VARCHAR(100)   NOT NULL,
    active      BOOLEAN        NOT NULL DEFAULT TRUE
);
